name: Jarvis Bulut Tarayici

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir otomatik çalışır!

jobs:
  tarama:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları İndir
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install requests beautifulsoup4 gspread oauth2client

      - name: Jarvis Botunu Çalıştır
        run: |
          python jarvis_bot.py
